/**
 * .gjbf binary format — encode / decode + fast point-in-polygon
 *
 * Only the current VERSION decodes — older layouts are rejected rather than
 * supported, since the IndexedDB cache key embeds the version (see useGeoJoin)
 * and every shipped .gjbf is regenerated by scripts/preprocess.mjs on a bump.
 *
 * Ring coordinates and ring bboxes are Int32 scaled by COORD_SCALE rather than
 * Float64 — half the bytes for ~11 cm precision. Point-in-polygon runs directly
 * in that scaled integer space; only map display converts back to degrees.
 *
 * Format (all little-endian):
 *   Header:         magic(4), version(4), numFeatures(4)
 *   Metadata:       numPolyGroups(4), numRings(4)
 *                   numProps(4), then per prop: keyLen(4)+keyStr(N)
 *   Bboxes:         Float64Array(numFeatures * 4)  — degrees
 *   PropValues:     per prop, per feature: strLen(4)+strBytes(N)  (column-major)
 *   PolyGroupStart: Uint32Array(numPolyGroups+1)
 *   RingGroupStart: Uint32Array(numRings+1)
 *   RingToFeature:  Uint32Array(numRings)
 *   Coord data:     per ring: numCoords(4) + Int32Array(numCoords*2)
 *   Ring bboxes:    Int32Array(numRings * 4)  — [minLon,minLat,maxLon,maxLat]
 */

import type { FeatureCollection, Feature, Polygon, MultiPolygon } from "geojson";

export interface GjbfData {
  numFeatures: number;
  numPolyGroups: number;
  numRings: number;
  /** Ordered property column keys (first = default). */
  propKeys: string[];
  /** Property key → per-feature values. Keyed by `propKeys`. */
  propColumns: Record<string, string[]>;
  /** Default column key (first of `propKeys`), or null if none. */
  propKey: string | null;
  /** Values of the default column — convenience alias for `propColumns[propKey]`. */
  propValues: string[];
  /** Per-feature bounding boxes in degrees [minLon,minLat,maxLon,maxLat]. */
  bboxes: Float64Array;
  polyGroupStart: Uint32Array;
  ringGroupStart: Uint32Array;
  ringToFeature: Uint32Array;
  /** Ring coordinates in COORD_SCALE units, not degrees. */
  coordArrays: Int32Array[];
  /** Per-ring bboxes in COORD_SCALE units. Length = numRings * 4. */
  ringBboxes: Int32Array;
  /** Grid refinement threshold for uploaded layers. Default 20. */
  refineThreshold: number;
  /** Grid sub-divisions per dense cell. Default 5. */
  subDivisions: number;
}

const MAGIC = 0x4642_4a47;
/** Bump on any layout change — cache keys embed it, so old entries go unread. */
export const VERSION = 4;

/**
 * Fixed-point scale for stored coordinates: degrees × 1e6, i.e. ~11 cm.
 * ±180° maps to ±1.8e8, comfortably inside Int32 range.
 *
 * All ring math happens in these units. Products stay well under 2^53, so the
 * doubles JS reads out of an Int32Array hold them exactly — the ray-casting
 * comparison is no less precise than it was in degrees, just scaled.
 *
 * MUST match COORD_SCALE in scripts/preprocess.mjs. A mismatch fails every
 * lookup in src/geo/__tests__/censusLayers.test.ts, which decodes real assets.
 */
const COORD_SCALE = 1e6;

const quantize = (deg: number) => Math.round(deg * COORD_SCALE);

// ── Decode (runtime) ────────────────────────────────────────────────

export function decodeGjbf(buffer: ArrayBuffer): GjbfData {
  const dec = new TextDecoder();
  let off = 0;
  const r32 = () => { const v = new DataView(buffer, off, 4).getUint32(0, true); off += 4; return v; };
  const rstr = () => { const sl = r32(); const s = sl > 0 ? dec.decode(new Uint8Array(buffer, off, sl)) : ""; off += sl; return s; };

  const magic = r32();
  if (magic !== MAGIC) throw new Error(`Bad magic: 0x${magic.toString(16)}`);
  const version = r32();
  if (version !== VERSION) throw new Error(`Bad version: ${version} (expected ${VERSION})`);
  const numFeatures = r32();
  const numPolyGroups = r32();
  const numRings = r32();

  // Property column keys
  const propKeys: string[] = [];
  const numProps = r32();
  for (let p = 0; p < numProps; p++) propKeys.push(rstr());

  // Use buffer.slice() everywhere for typed arrays — avoids "start offset should be a multiple of 8"
  const bboxes = new Float64Array(buffer.slice(off, off + numFeatures * 4 * 8));
  off += bboxes.byteLength;

  // Property values are column-major (each column = numFeatures strings)
  const propColumns: Record<string, string[]> = {};
  for (const key of propKeys) {
    const col: string[] = new Array(numFeatures);
    for (let i = 0; i < numFeatures; i++) col[i] = rstr();
    propColumns[key] = col;
  }

  const polyGroupStart = new Uint32Array(buffer.slice(off, off + (numFeatures + 1) * 4)); off += polyGroupStart.byteLength;
  const ringGroupStart = new Uint32Array(buffer.slice(off, off + (numPolyGroups + 1) * 4)); off += ringGroupStart.byteLength;
  const ringToFeature = new Uint32Array(buffer.slice(off, off + numRings * 4)); off += ringToFeature.byteLength;

  const coordArrays: Int32Array[] = [];
  for (let i = 0; i < numRings; i++) {
    const bytes = r32() * 2 * 4;
    coordArrays.push(new Int32Array(buffer.slice(off, off + bytes)));
    off += bytes;
  }

  const ringBboxes = new Int32Array(buffer.slice(off, off + numRings * 4 * 4));

  const propKey = propKeys.length ? propKeys[0] : null;
  const propValues = propKey ? propColumns[propKey] : [];

  return { numFeatures, numPolyGroups, numRings, propKeys, propColumns, propKey, propValues,
           bboxes, polyGroupStart, ringGroupStart, ringToFeature, coordArrays,
           ringBboxes, refineThreshold: 20, subDivisions: 5 };
}

/**
 * Reconstruct a GeoJSON FeatureCollection from decoded .gjbf — for map display,
 * so we never have to fetch the (much larger) raw .geojson source at runtime.
 * Mirrors the feature→polyGroup→ring walk used by `pointInFeature`.
 */
export function gjbfToFeatureCollection(data: GjbfData): FeatureCollection<Polygon | MultiPolygon> {
  const features: Feature<Polygon | MultiPolygon>[] = [];
  for (let fi = 0; fi < data.numFeatures; fi++) {
    const polys: number[][][][] = [];
    for (let pg = data.polyGroupStart[fi]; pg < data.polyGroupStart[fi + 1]; pg++) {
      const rings: number[][][] = [];
      for (let r = data.ringGroupStart[pg]; r < data.ringGroupStart[pg + 1]; r++) {
        const ca = data.coordArrays[r];
        const ring: number[][] = new Array(ca.length / 2);
        for (let k = 0, j = 0; k < ca.length; k += 2, j++) {
          ring[j] = [ca[k] / COORD_SCALE, ca[k + 1] / COORD_SCALE];
        }
        rings.push(ring);
      }
      polys.push(rings);
    }
    const geometry: Polygon | MultiPolygon = polys.length === 1
      ? { type: "Polygon", coordinates: polys[0] }
      : { type: "MultiPolygon", coordinates: polys };
    const properties: Record<string, string> = {};
    for (const key of data.propKeys) properties[key] = data.propColumns[key][fi];
    features.push({ type: "Feature", geometry, properties });
  }
  return { type: "FeatureCollection", features };
}

// ── Encode (on-the-fly for uploaded GeoJSON) ────────────────────────

export function geoJsonToGjbfBuffer(geojson: FeatureCollection): ArrayBuffer {
  const features = geojson.features.filter((f): f is Feature<Polygon | MultiPolygon> =>
    !!f.geometry && (f.geometry.type === "Polygon" || f.geometry.type === "MultiPolygon"));

  // Collect the union of property keys across all features (first-seen order).
  const propKeys: string[] = [];
  const seenKeys = new Set<string>();
  for (const f of features) {
    if (!f.properties) continue;
    for (const k of Object.keys(f.properties)) {
      if (!seenKeys.has(k)) { seenKeys.add(k); propKeys.push(k); }
    }
  }

  const bboxes: number[] = [];
  // Column-major property values: propColumns[p][fi]
  const propColumns: string[][] = propKeys.map(() => []);
  const coordArrays: Int32Array[] = [];
  const ringToFeature: number[] = [];
  const polyGroupStart: number[] = [];
  const ringGroupStart: number[] = [];
  const ringBboxes: number[] = []; // [minLon, minLat, maxLon, maxLat] per ring
  let polyGroupCount = 0;

  for (let fi = 0; fi < features.length; fi++) {
    const feat = features[fi];
    const bb = computeBbox(feat.geometry!.coordinates);
    bboxes.push(bb[0], bb[1], bb[2], bb[3]);
    for (let p = 0; p < propKeys.length; p++) {
      propColumns[p].push(String(feat.properties?.[propKeys[p]] ?? ""));
    }
    const polys = extractRings(feat.geometry!);
    polyGroupStart.push(polyGroupCount);
    for (const rings of polys) {
      ringGroupStart.push(coordArrays.length);
      polyGroupCount++;
      for (const ring of rings) {
        // Quantize first, then derive the bbox from the quantized ring so the
        // bbox prune can never reject a point the ring test would have accepted.
        const i32 = Int32Array.from(ring.flat(), quantize);
        coordArrays.push(i32);
        ringToFeature.push(fi);
        ringBboxes.push(...computeRingBbox(i32));
      }
    }
  }
  polyGroupStart.push(polyGroupCount);
  ringGroupStart.push(coordArrays.length);

  const nf = features.length, npg = ringGroupStart.length - 1, nr = coordArrays.length;

  // Compute buffer size
  const enc = new TextEncoder();
  const keyBytes = propKeys.map((k) => enc.encode(k));
  const colBytes = propColumns.map((col) => col.map((v) => enc.encode(v)));
  let size = 24; // 6 × uint32 header/metadata (magic,ver,nf,npg,nr,numProps)
  for (const b of keyBytes) size += 4 + b.length;
  size += nf * 4 * 8; // bboxes (Float64)
  for (const col of colBytes) for (const b of col) size += 4 + b.length;
  size += (nf + 1) * 4; // polyGroupStart
  size += (nr + 1) * 4;  // ringGroupStart
  size += nr * 4;        // ringToFeature
  for (const ca of coordArrays) size += 4 + ca.byteLength;
  size += nr * 4 * 4;    // ringBboxes (Int32) — v4+

  // Write buffer
  const buf = new ArrayBuffer(size);
  const ubuf = new Uint8Array(buf);
  let off = 0;

  const wu32 = (v: number) => { new DataView(buf, off, 4).setUint32(0, v, true); off += 4; };
  const wbytes = (src: Uint8Array) => { ubuf.set(src, off); off += src.length; };
  const wstr = (b: Uint8Array) => { wu32(b.length); wbytes(b); };

  wu32(MAGIC); wu32(VERSION); wu32(nf); wu32(npg); wu32(nr);
  wu32(propKeys.length);
  for (const b of keyBytes) wstr(b);
  wbytes(new Uint8Array(new Float64Array(bboxes).buffer));
  for (const col of colBytes) for (const b of col) wstr(b);
  wbytes(new Uint8Array(new Uint32Array(polyGroupStart).buffer));
  wbytes(new Uint8Array(new Uint32Array(ringGroupStart).buffer));
  wbytes(new Uint8Array(new Uint32Array(ringToFeature).buffer));
  for (const ca of coordArrays) {
    wu32(ca.length / 2);
    wbytes(new Uint8Array(ca.buffer, ca.byteOffset, ca.byteLength));
  }
  // v4+: ring bboxes (Int32, COORD_SCALE units)
  wbytes(new Uint8Array(new Int32Array(ringBboxes).buffer));

  return buf;
}

// ── Point-in-polygon (custom, fast, flat, with ring bbox pruning) ──

/** All args in COORD_SCALE units. */
function pointInRing(lon: number, lat: number, ring: Int32Array): boolean {
  let inside = false;
  const n = ring.length / 2;
  for (let i = 0, j = n - 1; i < n; j = i++) {
    const xi = ring[i * 2], yi = ring[i * 2 + 1];
    const xj = ring[j * 2], yj = ring[j * 2 + 1];
    if ((yi > lat) !== (yj > lat) && lon < xj + (xi - xj) * (lat - yj) / (yi - yj)) inside = !inside;
  }
  return inside;
}

/** `lon`/`lat` are degrees; they are quantized once here to match stored rings. */
export function pointInFeature(lon: number, lat: number, fi: number, data: GjbfData): boolean {
  let inside = false;
  const qLon = quantize(lon), qLat = quantize(lat);
  const ps = data.polyGroupStart[fi], pe = data.polyGroupStart[fi + 1];
  const rb = data.ringBboxes;

  for (let pg = ps; pg < pe; pg++) {
    const rs = data.ringGroupStart[pg], re = data.ringGroupStart[pg + 1];

    // Prune: skip if point outside outer ring's bounding box
    if (!pointInBbox(qLon, qLat, rb, rs)) continue;

    // Outer ring
    if (!pointInRing(qLon, qLat, data.coordArrays[rs])) continue;
    inside = !inside;

    // Holes (rings 1..N)
    for (let r = rs + 1; r < re; r++) {
      if (!pointInBbox(qLon, qLat, rb, r)) continue;
      if (pointInRing(qLon, qLat, data.coordArrays[r])) inside = !inside;
    }
  }
  return inside;
}

/** Quick AABB check: is the point inside the ring's bounding box? All COORD_SCALE units. */
function pointInBbox(lon: number, lat: number, bboxes: Int32Array, ringIdx: number): boolean {
  const off = ringIdx * 4;
  return lon >= bboxes[off] && lat >= bboxes[off + 1] &&
         lon <= bboxes[off + 2] && lat <= bboxes[off + 3];
}

// ── Helpers ─────────────────────────────────────────────────────────

function computeBbox(coords: unknown): [number, number, number, number] {
  let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;
  function visit(c: unknown) {
    if (!Array.isArray(c)) return;
    if (c.length >= 2 && typeof c[0] === "number" && typeof c[1] === "number") {
      const x = c[0] as number, y = c[1] as number;
      if (x < minX) minX = x; if (y < minY) minY = y;
      if (x > maxX) maxX = x; if (y > maxY) maxY = y;
      return;
    }
    for (const ch of c) visit(ch);
  }
  visit(coords);
  return [minX, minY, maxX, maxY];
}

/** Compute bounding box of a flat ring [lon,lat,lon,lat,...] */
function computeRingBbox(ring: Int32Array): [number, number, number, number] {
  let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;
  const n = ring.length;
  for (let i = 0; i < n; i += 2) {
    const x = ring[i], y = ring[i + 1];
    if (x < minX) minX = x;
    if (y < minY) minY = y;
    if (x > maxX) maxX = x;
    if (y > maxY) maxY = y;
  }
  return [minX, minY, maxX, maxY];
}

function extractRings(geom: Polygon | MultiPolygon): number[][][] {
  if (geom.type === "Polygon") return [geom.coordinates.map((r: unknown) => (r as number[][]).flat())];
  return geom.coordinates.map((p) => p.map((r: unknown) => (r as number[][]).flat()));
}